export default {content: [
  './index.html',
  './src/**/*.{js,ts,jsx,tsx}'
],
  theme: {
    extend: {
      colors: {
        'gray-50': 'var(--gray-50)',
        'gray-100': 'var(--gray-100)',
        'gray-200': 'var(--gray-200)',
        'gray-300': 'var(--gray-300)',
        'gray-400': 'var(--gray-400)',
        'gray-500': 'var(--gray-500)',
        'gray-600': 'var(--gray-600)',
        'gray-700': 'var(--gray-700)',
        'gray-800': 'var(--gray-800)',
        'gray-900': 'var(--gray-900)',
        'gray-950': 'var(--gray-950)',
        'blue-50': 'var(--blue-50)',
        'blue-300': 'var(--blue-300)',
        'blue-400': 'var(--blue-400)',
        'blue-500': 'var(--blue-500)',
        'blue-600': 'var(--blue-600)',
        'blue-700': 'var(--blue-700)',
        'blue-950': 'var(--blue-950)',
        'green-50': 'var(--green-50)',
        'green-300': 'var(--green-300)',
        'green-700': 'var(--green-700)',
        'green-950': 'var(--green-950)',
        'amber-50': 'var(--amber-50)',
        'amber-300': 'var(--amber-300)',
        'amber-800': 'var(--amber-800)',
        'amber-950': 'var(--amber-950)',
        'red-50': 'var(--red-50)',
        'red-300': 'var(--red-300)',
        'red-700': 'var(--red-700)',
        'red-950': 'var(--red-950)',
        background: 'var(--background)',
        surface: 'var(--surface)',
        'surface-elevated': 'var(--surface-elevated)',
        border: 'var(--border)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        accent: 'var(--accent)',
        'accent-hover': 'var(--accent-hover)',
        'accent-subtle': 'var(--accent-subtle)',
        'accent-subtle-foreground': 'var(--accent-subtle-foreground)',
        'focus-ring': 'var(--focus-ring)',
        'background-dark': 'var(--background-dark)',
        'surface-dark': 'var(--surface-dark)',
        'surface-elevated-dark': 'var(--surface-elevated-dark)',
        'border-dark': 'var(--border-dark)',
        'text-primary-dark': 'var(--text-primary-dark)',
        'text-secondary-dark': 'var(--text-secondary-dark)',
        'accent-dark': 'var(--accent-dark)',
        'accent-hover-dark': 'var(--accent-hover-dark)',
        'accent-subtle-dark': 'var(--accent-subtle-dark)',
        'accent-subtle-foreground-dark': 'var(--accent-subtle-foreground-dark)',
        'focus-ring-dark': 'var(--focus-ring-dark)',
        'success-background': 'var(--success-background)',
        'success-foreground': 'var(--success-foreground)',
        'warning-background': 'var(--warning-background)',
        'warning-foreground': 'var(--warning-foreground)',
        'danger-background': 'var(--danger-background)',
        'danger-foreground': 'var(--danger-foreground)',
        'info-background': 'var(--info-background)',
        'info-foreground': 'var(--info-foreground)',
        'success-background-dark': 'var(--success-background-dark)',
        'success-foreground-dark': 'var(--success-foreground-dark)',
        'warning-background-dark': 'var(--warning-background-dark)',
        'warning-foreground-dark': 'var(--warning-foreground-dark)',
        'danger-background-dark': 'var(--danger-background-dark)',
        'danger-foreground-dark': 'var(--danger-foreground-dark)',
        'info-background-dark': 'var(--info-background-dark)',
        'info-foreground-dark': 'var(--info-foreground-dark)',
        muted: 'var(--muted)',
        'muted-strong': 'var(--muted-strong)',
        'muted-hover': 'var(--muted-hover)',
        'on-accent': 'var(--on-accent)',
        'on-success': 'var(--on-success)',
        'on-danger': 'var(--on-danger)',
        'border-width-hairline': 'var(--border-width-hairline)',
        'border-width-default': 'var(--border-width-default)'
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)'
      }
    }
  }
}